version: '3'
services:  

  postgres_db:
    image: postgres:9.6.23-alpine3.14
    volumes:
      - explicit_postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust #use for developmentonly
      POSTGRES_USER: ${POSTGRES_USER:-starterkit}
      POSTGRES_DB: ${POSTGRES_DB:-starterkit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - 5442:5432

  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5999:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgres_db

volumes:
  explicit_postgres_vol:
    driver: local